In [4]:
import numpy as np 


In [5]:
arr = np.array([1,2,3,4,5,"prajwal"]);
print(arr,arr.dtype,type(arr));

['1' '2' '3' '4' '5' 'prajwal'] <U21 <class 'numpy.ndarray'>


In [37]:
arr_2d = np.array([[1,2,3],[1,2,3]]);

In [40]:
arr1 = np.zeros((3,3),dtype="int64");
print(arr1,arr1.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]] (3, 3)


In [64]:
arr2 = np.ones((4,4));
print(arr2,arr2.ndim);

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 2


In [47]:
arr3 = np.eye(3);
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [54]:
arr4 = np.arange(1,10,2.01);

In [62]:
arr4 = np.linspace(1,100,4)

In [63]:
print(arr4)

[  1.  34.  67. 100.]


In [66]:
float_arr = arr2.astype(np.int64);
print(float_arr);

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [69]:
arr7 = np.array([[1,2,3,4],[5,6,7,8]]);
new_arr = arr7.reshape(4,2)


(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [72]:
print(arr7[0][2])

3


In [74]:
idx = [1,2,5]
print(arr[idx])

['2' '3' 'prajwal']


In [ ]:
arri = arr[1:4];
print(arri);



['2' '3' '4']


In [9]:
print(arr)
arri[1]="prajwal";
print(arri)
print(arr);

['1' '2' 'prajwal' '4' '5' 'prajwal']
['2' 'prajwal' '4']
['1' '2' 'prajwal' '4' '5' 'prajwal']


In [15]:
np_arr = np.array([9,2,3,4,5,6]);
arr = np_arr[np_arr<3];
print(arr)

[2]


In [18]:
arr9 = np.array([1,23,4,5,6.1,7,7,8,8,8,4]);
print(arr9.dtype);


float64


In [23]:
#multidimension arrays 
arr2D = np.array([[1,2,3],[1,2,3],[4,5,6]]);
print(arr2D);
print(f"Sum={np.sum(arr2D,axis=1)}");

[[1 2 3]
 [1 2 3]
 [4 5 6]]
Sum=[ 6  6 15]


In [20]:
arr3D = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]);
print(arr3D,arr3D.ndim);

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 3


In [29]:
arr = np.array([[1,2,3],[4,5,6]]);
mean = np.mean(arr)
std = np.std(arr)

In [30]:
normalized = (arr-mean)/std;

In [31]:
print(normalized);

[[-1.46385011 -0.87831007 -0.29277002]
 [ 0.29277002  0.87831007  1.46385011]]


In [73]:
arr = np.array([1,2,-3,0,5,6,7]);
print(np.sum(arr));
print(np.max(arr));
print(np.min(arr));
print(np.prod(arr));
print(np.argmin(arr));
print(np.argmax(arr));
print(np.var(arr));
print(np.mean(arr));
print(np.median(arr));


18
7
-3
0
2
6
11.102040816326532
2.5714285714285716
2.0


In [75]:
arr = np.sort(arr);
print(arr);

[0 1 2 3 5 6 7]


In [1]:
print("hi")

hi
